### ISSUE TITLE
worker无法部署

### ISSUE THREAD

**Issue by cc1024** [Siujoeng-Lau/Workers-Proxy#10]
worker无法部署，提示语法错误，error 503。
截图：https://imgchr.com/i/KSdqsg

是冒号有问题吗？谢谢！

Win10，Cent Browser，版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)

**Comment by ainuoyan** [comment]
用Wrangler部署

**Comment by Siujoeng-Lau** [comment]
https://github.com/Siujoeng-Lau/Workers-Proxy/blob/master/src/index.js
用最新版...

**Comment by cc1024** [comment]
用新的index.js，OK了。谢谢@Siujoeng-Lau
