### ISSUE TITLE
About cache-control

### ISSUE THREAD

**Issue by ifyour** [Siujoeng-Lau/Workers-Proxy#11]
**Describe the bug**
The image is loaded for the first time and the cache is invalid.

**To Reproduce**
The first time you enter the website, the cache is invalid.

**Screenshots**
![cach-error](https://user-images.githubusercontent.com/15377484/68536971-05c59000-0397-11ea-861e-c49a5f52df6f.jpg)

**Additional context**
https://github.com/Siujoeng-Lau/Workers-Proxy/blob/e7c0423c8e0763dd4cc226efd914bb4a62c5d5d8/src/index.js#L74

The cache-control here should probably not be fixed.

Maybe it should be configured as needed in Cloudflare. Just a suggestion.
![image](https://user-images.githubusercontent.com/15377484/68536987-53da9380-0397-11ea-82c8-0bb32674ca1c.png)

**Comment by Siujoeng-Lau** [comment]
Thanks for your feedback.
Already fixed in the lastest commit.
