### ISSUE TITLE
如何代理端口

### ISSUE THREAD

**Issue by blackjelly** [Siujoeng-Lau/Workers-Proxy#12]
如何代理非标准端口？比如xxx.com:8886

**Comment by Siujoeng-Lau** [comment]
试试直接在url里加上端口
const upstream = 'www.google.com:25565'

**Comment by blackjelly** [comment]
尝试过，我想代理我的DDNS来替代NGINX的反向代理，但是试了很多次都不行。

**Comment by Siujoeng-Lau** [comment]
试一下最新的版本, 如果反代的端口没开 HTTPS, 就把 `https` 设置成 `false`.
Upstream 直接填 'www.google.com:25565' 这样格式就行.
