### ISSUE TITLE
设置utf8 编码以后，代理其他语言编码，替换的txt 无效。还乱码。

### ISSUE THREAD

**Issue by hsmw** [Siujoeng-Lau/Workers-Proxy#13]
(content_type.includes('text/html') && content_type.includes('utf8')

例如日本乐天的站  search.rakuten.co.jp
<meta http-equiv="Content-type" content="text/html; charset=euc-jp">

修改
content_type.includes('euc-jp')  直接页面乱码了。

**Comment by Siujoeng-Lau** [comment]
emm的确有这个问题·
待我解决一下

**Comment by Siujoeng-Lau** [comment]
暂时没找到有效的解决方法... Workers 的文本替换似乎只支持 UTF-8
