### ISSUE TITLE
如何反代二级目录？

### ISSUE THREAD

**Issue by sbblog** [Siujoeng-Lau/Workers-Proxy#16]
试了下，二级域名没问题，但是二级目录怎么实现？
二级目录，三级目录这种，const upstream应该怎么填写。

**Comment by Siujoeng-Lau** [comment]
暂时无法实现, 打算更新一下...

**Comment by sbblog** [comment]
感谢

**Comment by Siujoeng-Lau** [comment]
2481933d4aa038b9f3b2358eddd6759ff40b34a2
最新的版本增加了一个upstream_path 可以设置二级目录
欢迎测试

**Comment by sbblog** [comment]
测试没问题。
