### ISSUE TITLE
[Enhancement] Port customize 自定义端口

### ISSUE THREAD

**Issue by W-MS** [Siujoeng-Lau/Workers-Proxy#17]
源站加端口可以预览但单独在浏览器打开就不行.

**Comment by Siujoeng-Lau** [comment]
目前版本支持自定义端口, 示例配置:
`const upstream = 'portquiz.net:8777'`

**Comment by CrazyBoyFeng** [comment]
我也遇到这个问题了， `upstream: 'http://api.yx56.cn:8080'` 预览和测试是正常的，但是部署后发现它连接的是 80 端口。
上面的 `upstream: 'portquiz.net:8777'` 我试了是正常请求了 8777，真让人理解不了。

**Comment by CrazyBoyFeng** [comment]
经过我的[多番测试](https://community.cloudflare.com/t/workers-can-not-fetch-port-8080/237487/6?u=crazyboyfeng)，cloudflare workers 在 fetch http 协议的 url 时，实际上统统都会去访问 80 端口。而 https 协议的 url 是能够正常访问 443 以外的端口的。  
为什么上面那个 `http://portquiz.net` 是特例，据我推测（没找到源码），它是把 `request.headers['host']` 带的端口取出打印了。实际上 cloudflare worker 还是访问的 80，只是 url 里的端口号被写进 `request.headers['host']` 里面原样传给服务器了。
