### ISSUE TITLE
反代谷歌表单不成功

### ISSUE THREAD

**Issue by taocwang** [Siujoeng-Lau/Workers-Proxy#21]
反代谷歌表单不成功，网页可以浏览，但是无法填写提交，大大能否看看

**Comment by Siujoeng-Lau** [comment]
看了一下, 是 www.gstatic.com 的几个JavaScript文件无法加载.
你可以再建一个 worker, 专门用于反代 www.gstatic.com.
然后在反代表单的 worker 中把 www.gstatic.com 替换成反代域名.

**Comment by TerenceLiu98** [comment]
@Berkeley-Reject 你好，我根据 README 上的指示添加了 `www.gstatic.com` 到 `replace_dict` 但是在打开的时候一样无法填写和提交，然后看到 console 里没有反代 www.gstatic.com/_/freebird/* 成功。
我了下我反代的 `gstatic.workers.dev/_/freebird/*` 是可以访问的，想问问这是什么情况.

另，想问下 @taocwang 反代表单成功了吗？有没有遇到这种问题 :)

**Comment by taocwang** [comment]
@TerenceLiu98 遇到的情况和你一样，反代没有成功!
