### ISSUE TITLE
请教如何反代onedrive

### ISSUE THREAD

**Issue by whyun1** [Siujoeng-Lau/Workers-Proxy#22]
想反代onedrive.live.com。谢谢

**Comment by wangchunin** [comment]
找到方法了吗，我也想反代onedrive

**Comment by Siujoeng-Lau** [comment]
暂时没找到好方法...

**Comment by wangchunin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我已经放弃了^-^
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1104436919
                            
                    
                        
                            
                                    1104436919@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年4月8日 20:43，Xiaoyang Liu<notifications@github.com> 写道： 




暂时没找到好方法...



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by movny** [comment]
office business可用
我目前用
cdn.incite.ren[https://cdn.incite.ren]反代Oneindex网站movn-lib.herokuapp.com
cdn1.incite.ren反代下载地址officeacid-my.sharepoint.com

cdn.incite.ren :
```js
// Website you intended to retrieve for users.
const upstream = 'movn-lib.herokuapp.com'

// Custom pathname for the upstream website.
const upstream_path = '/'

// Website you intended to retrieve for users using mobile devices.
const upstream_mobile = 'movn-lib.herokuapp.com'

// Countries and regions where you wish to suspend your service.
const blocked_region = []

// IP addresses which you wish to block from using your service.
const blocked_ip_address = []

// Whether to use HTTPS protocol for upstream address.
const https = true

// Replace texts.
const replace_dict = {
    '$upstream': '$custom_domain',
    '//officeacid-my.sharepoint.com': '//cdn1.incite.ren',
    '//movn-lib.herokuapp.com': '//cdn.incite.ren'
}
......
```
