### ISSUE TITLE
反代 dropbox 分享地址 dl.dropboxusercontent.com  轮流出现 Error 1101

### ISSUE THREAD

**Issue by shijunyi** [Siujoeng-Lau/Workers-Proxy#24]
**Describe the bug**
反代 dropbox 分享地址 “dl.dropboxusercontent.com”  

**轮流出现 Error 1101 ，就是刷新一下可以，再刷新就出现 Error 1101错误，再刷新又可以出来。**

 win10  chrome 70 浏览器  IE 皆会出现

**代码如下**  
`// Website you intended to retrieve for users.
const upstream = 'dl.dropboxusercontent.com'

// Custom pathname for the upstream website.
const upstream_path = '/'

// Website you intended to retrieve for users using mobile devices.
const upstream_mobile = 'dl.dropboxusercontent.com'

// Countries and regions where you wish to suspend your service.
const blocked_region = ['KP', 'SY', 'PK', 'CU']

// IP addresses which you wish to block from using your service.
const blocked_ip_address = ['0.0.0.0', '127.0.0.1']

// Whether to use HTTPS protocol for upstream address.
const https = true

// Replace texts.
const replace_dict = {
    '$upstream': '$custom_domain',
   
}
`
**贴下反代后得网址**
原地址：https://dl.dropboxusercontent.com/s/ofqd7dy7s9wcw62/ERnU6dyU8AAalxn.jpg_orig.jpeg

反代后地址：https://dropbox.sjy.workers.dev/s/ofqd7dy7s9wcw62/ERnU6dyU8AAalxn.jpg_orig.jpeg

**Screenshots**

![2020-03-12_192734.jpg](https://i.loli.net/2020/03/12/vnD2GAaYlOc15q9.jpg)

**Additional context**

**Comment by Siujoeng-Lau** [comment]
我用我的域名试了一下, 好像一直能刷新出来? cdn.reserve-proxy.live
代码和你的一样.

**Comment by shijunyi** [comment]
谢谢回复，那可能是我这边网络问题。手机网络也是都可以刷出来。
