### ISSUE TITLE
在访问GitHub单个文件时500错误

### ISSUE THREAD

**Issue by woytu** [Siujoeng-Lau/Workers-Proxy#26]
**Describe the bug**

代理GitHub，访问单个文件的源（raw）时第一次response报500错误，页面报`Error 1101`

**To Reproduce**

https://github.bajins.com/xiaotianwl/v2ray_vps/raw/master/v2ray

**Screenshots**
![image](https://user-images.githubusercontent.com/30252550/77604058-9074e900-6f4c-11ea-9dbd-946873516ba6.png)

**Additional context**
另外在代码中添加以下代码能加速访问单个页面的速度：

```js
if(response_headers.get("x-pjax-url")){
      new_response_headers.set("x-pjax-url",response_headers.get("x-pjax-url").replace("//github.com",$custom_domain));
 }
```

**Comment by Siujoeng-Lau** [comment]
应该是缓存的问题, F12 开启 Disable Cache 后就没这个问题了, 我看一下解决方法.
