### ISSUE TITLE
反代 Oracle 对象储存时, 文件无法下载 (出现乱码)

### ISSUE THREAD

**Issue by wnark** [Siujoeng-Lau/Workers-Proxy#29]
反代目标为我的甲骨文对象存储网址：`ax9advmduxh0.compat.objectstorage.us-phoenix-1.oraclecloud.com`
反代目标目录：/US
因为甲骨文对象存储不支持防盗链，因此我准备使用cloudflare的cf worker来反代实现防盗链

目标文件链接：
`https://ax9advmduxh0.compat.objectstorage.us-phoenix-1.oraclecloud.com/US/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv`

worker域名：`oracle-us.wnark.workers.dev`

生成的域名：
`https://oracle-us.wnark.workers.dev/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv`

调试阶段提示：
```
Uncaught (in promise) TypeError: Cannot read property 'includes' of null
    at fetchAndApply (worker.js:103)
fetchAndApply @ worker.js:103
Promise.catch (async)
(anonymous) @ worker.js:29
Uncaught (in response) TypeError: Cannot read property 'includes' of null
```
![image](https://user-images.githubusercontent.com/24355466/79314074-db729280-7f33-11ea-92a2-0270162dd522.png)

浏览器访问提示Error 1101：
![image](https://user-images.githubusercontent.com/24355466/79313695-4d96a780-7f33-11ea-8355-94e5af493491.png)

对象存储目录树为：
![image](https://user-images.githubusercontent.com/24355466/79313737-61420e00-7f33-11ea-9062-a38cc98bca21.png)

很奇怪，只有`/视频/《我的三体》 伪（zhong）剧（级）场（pian）版.flv`出现这个问题，其他文件我修改文件名，也放到中文目录，加特殊字符，都不会复现，只有这个文件可以复现。

直接用对象存储直链可下载，文件应该没问题。

为了您方便调试，我这个文件就留在这供您测试吧，您调试好后我再删掉。

**Comment by Siujoeng-Lau** [comment]
似乎是因为 /`视频/《我的三体》 伪（zhong）剧（级）场（pian）版.flv` 没有返回 'content-type', 导致错误. 试一下最新版本.
c6d72a6c3b1f0b294716ad4470b844cbacff11d3

**Comment by wnark** [comment]
> 似乎是因为 /`视频/《我的三体》 伪（zhong）剧（级）场（pian）版.flv` 没有返回 'content-type', 导致错误. 试一下最新版本.
> [c6d72a6](https://github.com/Siujoeng-Lau/Workers-Proxy/commit/c6d72a6c3b1f0b294716ad4470b844cbacff11d3)

你好，修复了一半，目前出现了新的bug：
如果是访问cf worker分配给我的域名，目前可以下载：
`http://oracle-us.wnark.workers.dev/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv`

但当我使用其他路由访问
`oracle-us.wnark.com/*`
`http://oracle-us.wnark.com/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv`
在chrome浏览器貌似是作为文本打开了，而在火狐是正常的弹出下载框

![image](https://user-images.githubusercontent.com/24355466/79324468-45923400-7f42-11ea-88e4-92f38653abbe.png)
![image](https://user-images.githubusercontent.com/24355466/79324570-635f9900-7f42-11ea-8a56-9bb81a7cad7d.png)

**Comment by Siujoeng-Lau** [comment]
已经解决. 造成问题的原因是 甲骨文对象存储 在 Response Header 中没有提供该文件的 "content-type", Cloudflare 的 No-Sniff Header 功能禁止 Chrome 主动判断文件类型. (Chrome 无法识别该文件为视频文件, 所以无法下载)

解决方法:
1. 进入 Cloudflare 对应域名的 SSL/TLS 设置
2. HTTP Strict Transport Security (HSTS) 选择 Change HSTS Settings
3. No-Sniff Header 设置为 Off

[测试链接 (https://cdn.reverse-proxy.live)](https://cdn.reverse-proxy.live/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv)

**Comment by wnark** [comment]
> 已经解决. 造成问题的原因是 甲骨文对象存储 在 Response Header 中没有提供该文件的 "content-type", Cloudflare 的 No-Sniff Header 功能禁止 Chrome 主动判断文件类型. (Chrome 无法识别该文件为视频文件, 所以无法下载)
> 
> 解决方法:
> 
> 1. 进入 Cloudflare 对应域名的 SSL/TLS 设置
> 2. HTTP Strict Transport Security (HSTS) 选择 Change HSTS Settings
> 3. No-Sniff Header 设置为 Off
> 
> [测试链接 (https://cdn.reverse-proxy.live)](https://cdn.reverse-proxy.live/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv)

你好，这个视频问题确认已解决，配置了hsts后可以正常使用我的域名下载。但现在出现了新的问题。
图片直链：`https://ax9advmduxh0.compat.objectstorage.us-phoenix-1.oraclecloud.com/US/gravatar-120x120.png`

使用worker分配的域名`https://oracle-us.wnark.workers.dev/gravatar-120x120.png`可以正常访问
![image](https://user-images.githubusercontent.com/24355466/79329699-d705a400-7f4a-11ea-994b-f2b2a1563748.png)
但使用我自己的域名`https://oracle-us.wnark.com/gravatar-120x120.png`后，出现防盗链：1011错误
![image](https://user-images.githubusercontent.com/24355466/79329813-04525200-7f4b-11ea-847a-e21411445db8.png)

即使worker真的有防盗链，也不会单单针对图片吧

**Comment by wnark** [comment]
这个bug可以重复出现：另一个图片
`https://ax9advmduxh0.compat.objectstorage.us-phoenix-1.oraclecloud.com/US/69547025.jpg`

对应的链接：
`https://oracle-us.wnark.com/69547025.jpg`

也出现了相同现象：
```

Error 1011 Ray ID: 58452c98936eed6b • 2020-04-15 11:02:25 UTC
Access denied
What happened?

The owner of this website (oracle-us.wnark.com) does not allow hotlinking to that resource (/US/69547025.jpg).

```

![image](https://user-images.githubusercontent.com/24355466/79330305-e507f480-7f4b-11ea-9b85-cd8625c2c1b6.png)

**Comment by Siujoeng-Lau** [comment]
[我自己的域名](https://cdn.reverse-proxy.live/gravatar-120x120.png)
似乎没有出现问题

**Comment by wnark** [comment]
> [我自己的域名](https://cdn.reverse-proxy.live/gravatar-120x120.png) 似乎没有出现问题
> Cloudflare 的防盗链确实只针对图片
> 把 74 行删了就行: `new_request_headers.set('Referer', url.hostname);`

`new_request_headers.set('Referer', url.hostname);`删除后症状消失，我的这个域名是通过CFP添加的，可能从CFP添加的域名没有进入worker的白名单内。导致出现奇葩的情况。我这边把配置全删完全重新部署下试试看

**Comment by wnark** [comment]
完全重新部署测试，目前没出现新的Bug,感谢大佬的项目

**Comment by liberty-song** [comment]
> 已经解决. 造成问题的原因是 甲骨文对象存储 在 Response Header 中没有提供该文件的 "content-type", Cloudflare 的 No-Sniff Header 功能禁止 Chrome 主动判断文件类型. (Chrome 无法识别该文件为视频文件, 所以无法下载)
> 
> 解决方法:
> 
> 1. 进入 Cloudflare 对应域名的 SSL/TLS 设置
> 2. HTTP Strict Transport Security (HSTS) 选择 Change HSTS Settings
> 3. No-Sniff Header 设置为 Off
> 
> [测试链接 (https://cdn.reverse-proxy.live)](https://cdn.reverse-proxy.live/%E8%A7%86%E9%A2%91/%E3%80%8A%E6%88%91%E7%9A%84%E4%B8%89%E4%BD%93%E3%80%8B%20%E4%BC%AA%EF%BC%88zhong%EF%BC%89%E5%89%A7%EF%BC%88%E7%BA%A7%EF%BC%89%E5%9C%BA%EF%BC%88pian%EF%BC%89%E7%89%88.flv)

感谢解答. 我也遇到了这个问题, 原来是 CloudFlare 配置出错了.

**Comment by Berkeley-Reject** [comment]
> 3\. No-Sniff Header

这个设置的用途是防止两项攻击, 但是甲骨文对象储存不返回 `content-type`, 只能让浏览器自行判断.

> Attacks Countered

> MIME Confusion Attack enables attacks via user generated content sites by allowing users uploading malicious code that is then executed by browsers which will interpret the files using alternate content types, e.g. implicit application/javascript vs. explicit text/plain. This can result in a "drive-by download" attack which is a common attack vector for phishing. Sites that host user generated content should use this header to protect their users. This is mentioned by VeraCode and OWASP which says the following:

> This reduces exposure to drive-by download attacks and sites serving user uploaded content that, by clever naming, could be treated by MSIE as executable or dynamic HTML files.

> Unauthorized Hotlinking can also be enabled by Content-Type sniffing. By hotlinking to sites with resources for one purpose, e.g. viewing, apps can rely on content-type sniffing and generate a lot of traffic on sites for another purpose where it may be against their terms of service, e.g. GitHub displays JavaScript code for viewing, but not for execution:

> Some pesky non-human users (namely computers) have taken to "hotlinking" assets via the raw view feature -- using the raw URL as the src for a <script> or <img> tag. The problem is that these are not static assets. The raw file view, like any other view in a Rails app, must be rendered before being returned to the user. This quickly adds up to a big toll on performance. In the past we've been forced to block popular content served this way because it put excessive strain on our servers.
